tech_patterns = {
            "WordPress": ["wp-content", "wp-includes", "wordpress"],
            "React": ["react", "reactjs", "jsx"],
            "Angular": ["angular", "ng-"],
            "Vue.js": ["vue", "vuejs"],
            "Bootstrap": ["bootstrap"],
            "jQuery": ["jquery"],
            "PHP": ["php"],
            "Laravel": ["laravel"],
            "Django": ["django"],
            "Flask": ["flask"],
            "Node.js": ["node", "nodejs"],
            "Express": ["express"],
            "MongoDB": ["mongodb", "mongo"],
            "MySQL": ["mysql"],
            "PostgreSQL": ["postgresql", "postgres"],
            "Ruby on Rails": ["rails", "ruby on rails"],
            "Shopify": ["shopify"],
            "Wix": ["wix"],
            "Squarespace": ["squarespace"],
            "Webflow": ["webflow"],
            "Gatsby": ["gatsby"],
            "Next.js": ["next.js", "nextjs"],
            "Nuxt.js": ["nuxt.js", "nuxtjs"],
            "Svelte": ["svelte"],
            "TypeScript": ["typescript"],
            "Tailwind CSS": ["tailwind"],
            "Material UI": ["material-ui", "mui"],
            "GraphQL": ["graphql"],
            "Redux": ["redux"],
            "Firebase": ["firebase"],
            "AWS": ["aws", "amazon web services"],
            "Google Cloud": ["gcp", "google cloud"],
            "Azure": ["azure", "microsoft azure"],
            "Cloudflare": ["cloudflare"],
            "Netlify": ["netlify"],
            "Vercel": ["vercel"],
            "Heroku": ["heroku"],
            "Docker": ["docker"],
            "Kubernetes": ["kubernetes", "k8s"],
            "Webpack": ["webpack"],
            "Babel": ["babel"],
            "ESLint": ["eslint"],
            "Jest": ["jest"],
            "Mocha": ["mocha"],
            "Cypress": ["cypress"],
            "Google Analytics": ["google analytics", "ga"],
            "Stripe": ["stripe"],
            "PayPal": ["paypal"],
            "Algolia": ["algolia"],
            "Contentful": ["contentful"],
            "Sanity": ["sanity.io", "sanity"],
            "Drupal": ["drupal"],
            "Joomla": ["joomla"],
            "Magento": ["magento"],
            "WooCommerce": ["woocommerce"],
            "PrestaShop": ["prestashop"],
            "OpenCart": ["opencart"],
            "Elementor": ["elementor"],
            "Divi": ["divi"],
            "Gutenberg": ["gutenberg"],
            "SASS/SCSS": ["sass", "scss"],
            "Less": ["less"],
            "Styled Components": ["styled-components", "styled components"],
            "Emotion": ["emotion"],
            "Chakra UI": ["chakra"],
            "Ant Design": ["antd", "ant design"],
            "Semantic UI": ["semantic-ui", "semantic ui"],
            "Bulma": ["bulma"],
            "Foundation": ["foundation"],
            "Alpine.js": ["alpine.js", "alpinejs"],
            "Stimulus": ["stimulus"],
            "Ember": ["ember"],
            "Backbone.js": ["backbone"],
            "Meteor": ["meteor"],
            "Socket.io": ["socket.io", "socketio"],
            "D3.js": ["d3.js", "d3"],
            "Three.js": ["three.js", "threejs"],
            "Chart.js": ["chart.js", "chartjs"],
            "Highcharts": ["highcharts"],
            "Plotly": ["plotly"],
            "Leaflet": ["leaflet"],
            "Mapbox": ["mapbox"],
            "Auth0": ["auth0"],
            "Okta": ["okta"],
            "Sentry": ["sentry"],
            "New Relic": ["newrelic", "new relic"],
            "Datadog": ["datadog"],
            "Amplitude": ["amplitude"],
            "Mixpanel": ["mixpanel"],
            "Hotjar": ["hotjar"],
            "Intercom": ["intercom"],
            "Zendesk": ["zendesk"],
            "Hubspot": ["hubspot"],
            "Mailchimp": ["mailchimp"],
            "SendGrid": ["sendgrid"],
            "Twilio": ["twilio"],
            "Cloudinary": ["cloudinary"],
            "Akamai": ["akamai"],
            "Fastly": ["fastly"],
            "Vimeo": ["vimeo"],
            "YouTube": ["youtube"],
            "Disqus": ["disqus"],
            "Discourse": ["discourse"],
            "Ghost": ["ghost"],
            "Medium": ["medium"],
            "Webmentions": ["webmention"],
            "IndieWeb": ["indieweb"],
            "Microformats": ["microformats", "h-card", "h-entry"],
            "JSON-LD": ["json-ld", "jsonld"],
            "Schema.org": ["schema.org", "schema"],
            "Open Graph": ["og:"],
            "Twitter Cards": ["twitter:"],
            "AMP": ["amp-", "accelerated mobile pages"],
            "PWA": ["progressive web app", "service-worker.js", "manifest.json"],
            "WebAssembly": ["wasm", "webassembly"],
            "WebGL": ["webgl"],
            "WebRTC": ["webrtc"],
            "WebSockets": ["websocket"],
            "Web Components": ["custom-elements", "shadow-dom", "web components"],
            "Lit": ["lit-element", "lit-html", "lit"],
            "Stencil": ["stencil"],
            "Polymer": ["polymer"],
            "Ionic": ["ionic"],
            "Capacitor": ["capacitor"],
            "Cordova": ["cordova"],
            "Flutter": ["flutter"],
            "React Native": ["react-native", "react native"],
            "Swift": ["swift"],
            "Kotlin": ["kotlin"],
            "Unity": ["unity"],
            "Unreal Engine": ["unreal"],
            "Godot": ["godot"],
            "Electron": ["electron"],
            "Tauri": ["tauri"],
            "NW.js": ["nw.js", "nwjs"],
            "Deno": ["deno"],
            "Bun": ["bun"],
            "Vite": ["vite"],
            "Parcel": ["parcel"],
            "Rollup": ["rollup"],
            "esbuild": ["esbuild"],
            "SWC": ["swc"],
            "Rome": ["rome"],
            "Prettier": ["prettier"],
            "Husky": ["husky"],
            "Storybook": ["storybook"],
            "Nx": ["nx"],
            "Turborepo": ["turborepo"],
            "Lerna": ["lerna"],
            "pnpm": ["pnpm"],
            "Yarn": ["yarn"],
            "npm": ["npm"],
            "Astro": ["astro"],
            "Remix": ["remix"],
            "SolidJS": ["solid-js", "solidjs"],
            "Preact": ["preact"],
            "Qwik": ["qwik"],
            "htmx": ["htmx"],
            "Alpine.js": ["alpine.js", "alpinejs"],
            "Hotwire": ["hotwire", "turbo", "stimulus"],
            "LiveView": ["liveview"],
            "Livewire": ["livewire"],
            "Inertia.js": ["inertia", "inertiajs"],
            "tRPC": ["trpc"],
            "Prisma": ["prisma"],
            "Sequelize": ["sequelize"],
            "TypeORM": ["typeorm"],
            "Mongoose": ["mongoose"],
            "Drizzle": ["drizzle-orm", "drizzle"],
            "Supabase": ["supabase"],
            "Hasura": ["hasura"],
            "Directus": ["directus"],
            "Strapi": ["strapi"],
            "KeystoneJS": ["keystone"],
            "Payload CMS": ["payload cms", "payload"],
            "Craft CMS": ["craft cms", "craft"],
            "Statamic": ["statamic"],
            "Kirby": ["kirby"],
            "Wagtail": ["wagtail"],
            "Umbraco": ["umbraco"],
            "Kentico": ["kentico"],
            "Sitecore": ["sitecore"],
            "Adobe Experience Manager": ["aem", "adobe experience manager"],
            "Contentstack": ["contentstack"],
            "Storyblok": ["storyblok"],
            "DatoCMS": ["datocms", "dato cms"],
            "Prismic": ["prismic"],
            "Builder.io": ["builder.io"],
            "Webflow CMS": ["webflow cms"],
            "Plasmic": ["plasmic"],
            "Framer": ["framer"],
            "Figma": ["figma"],
            "Sketch": ["sketch"],
            "Adobe XD": ["adobe xd", "xd"],
            "InVision": ["invision"],
            "Zeplin": ["zeplin"],
            "Abstract": ["abstract"],
            "Miro": ["miro"],
            "Notion": ["notion"],
            "Airtable": ["airtable"],
            "Coda": ["coda"],
            "Monday": ["monday"],
            "Asana": ["asana"],
            "Trello": ["trello"],
            "Jira": ["jira"],
            "Linear": ["linear"],
            "ClickUp": ["clickup"],
            "Basecamp": ["basecamp"],
            "Slack": ["slack"],
            "Discord": ["discord"],
            "Microsoft Teams": ["teams", "microsoft teams"],
            "Google Workspace": ["google workspace"],
            "Microsoft 365": ["microsoft 365", "office 365"],
            "Zoom": ["zoom"],
            "Google Meet": ["google meet", "meet"],
            "Microsoft Teams": ["teams", "microsoft teams"],
            "WebEx": ["webex"],
            "GoToMeeting": ["gotomeeting"],
            "BlueJeans": ["bluejeans"],
            "Whereby": ["whereby"],
            "Calendly": ["calendly"],
            "Google Calendar": ["google calendar"],
            "Microsoft Outlook": ["outlook"],
            "Salesforce": ["salesforce"],
            "HubSpot": ["hubspot"],
            "Marketo": ["marketo"],
            "Mailchimp": ["mailchimp"],
            "Klaviyo": ["klaviyo"],
            "Brevo": ["brevo", "sendinblue"],
            "ActiveCampaign": ["activecampaign"],
            "ConvertKit": ["convertkit"],
            "Constant Contact": ["constant contact"],
            "Campaign Monitor": ["campaign monitor"],
            "GetResponse": ["getresponse"],
            "AWeber": ["aweber"],
            "Drip": ["drip"],
            "Omnisend": ["omnisend"],
            "Iterable": ["iterable"],
            "Customer.io": ["customer.io"],
            "Segment": ["segment"],
            "Google Tag Manager": ["gtm", "google tag manager"],
            "Tealium": ["tealium"],
            "Ensighten": ["ensighten"],
            "Adobe Analytics": ["adobe analytics"],
            "Matomo": ["matomo", "piwik"],
            "Plausible": ["plausible"],
            "Fathom": ["fathom"],
            "Simple Analytics": ["simple analytics"],
            "Heap": ["heap"],
            "FullStory": ["fullstory"],
            "LogRocket": ["logrocket"],
            "Mouseflow": ["mouseflow"],
            "Crazy Egg": ["crazy egg", "crazyegg"],
            "Optimizely": ["optimizely"],
            "VWO": ["vwo", "visual website optimizer"],
            "AB Tasty": ["ab tasty", "abtasty"],
            "Convert": ["convert.com"],
            "Unbounce": ["unbounce"],
            "Instapage": ["instapage"],
            "Leadpages": ["leadpages"],
            "Landingi": ["landingi"],
            "Webflow": ["webflow"],
            "Bubble": ["bubble.io", "bubble"],
            "Glide": ["glide"],
            "Adalo": ["adalo"],
            "Softr": ["softr"],
            "Carrd": ["carrd"],
            "Tilda": ["tilda"],
            "Readymag": ["readymag"],
            "Framer": ["framer"],
            "Squarespace": ["squarespace"],
            "Wix": ["wix"],
            "Shopify": ["shopify"],
            "BigCommerce": ["bigcommerce"],
            "WooCommerce": ["woocommerce"],
            "Magento": ["magento"],
            "PrestaShop": ["prestashop"],
            "OpenCart": ["opencart"],
            "Salesforce Commerce Cloud": ["salesforce commerce", "demandware"],
            "Adobe Commerce": ["adobe commerce"],
            "Swell": ["swell.is", "swell"],
            "Medusa": ["medusajs", "medusa"],
            "CommerceJS": ["commerce.js", "commercejs"],
            "Snipcart": ["snipcart"],
            "Stripe": ["stripe"],
            "PayPal": ["paypal"],
            "Square": ["square"],
            "Adyen": ["adyen"],
            "Braintree": ["braintree"],
            "Klarna": ["klarna"],
            "Affirm": ["affirm"],
            "Afterpay": ["afterpay"],
            "Clearpay": ["clearpay"],
            "Zip": ["zip"],
            "Sezzle": ["sezzle"],
            "Amazon Pay": ["amazon pay"],
            "Google Pay": ["google pay"],
            "Apple Pay": ["apple pay"],
            "Shop Pay": ["shop pay"],
            "Bolt": ["bolt"],
            "Fast": ["fast"],
            "Algolia": ["algolia"],
            "Elasticsearch": ["elasticsearch"],
            "Meilisearch": ["meilisearch"],
            "Typesense": ["typesense"],
            "Solr": ["solr"],
            "Coveo": ["coveo"],
            "Constructor.io": ["constructor.io"],
            "Klevu": ["klevu"],
            "Searchspring": ["searchspring"],
            "Nosto": ["nosto"],
            "Dynamic Yield": ["dynamic yield"],
            "Bloomreach": ["bloomreach"],
            "Sitecore": ["sitecore"],
            "Contentful": ["contentful"],
            "Sanity": ["sanity"],
            "Strapi": ["strapi"],
            "Contentstack": ["contentstack"],
            "Storyblok": ["storyblok"],
            "Prismic": ["prismic"],
            "DatoCMS": ["datocms"],
            "Kontent.ai": ["kontent.ai", "kentico kontent"],
            "Agility CMS": ["agility cms"],
            "Builder.io": ["builder.io"],
            "Plasmic": ["plasmic"],
            "Webiny": ["webiny"],
            "Ghost": ["ghost"],
            "WordPress": ["wordpress"],
            "Drupal": ["drupal"],
            "Joomla": ["joomla"],
            "TYPO3": ["typo3"],
            "Umbraco": ["umbraco"],
            "Sitefinity": ["sitefinity"],
            "Kentico": ["kentico"],
            "Episerver": ["episerver", "optimizely cms"],
            "Adobe Experience Manager": ["aem", "adobe experience manager"],
            "Sitecore": ["sitecore"],
            "Acquia": ["acquia"],
            "Pantheon": ["pantheon"],
            "WP Engine": ["wp engine", "wpengine"],
            "Kinsta": ["kinsta"],
            "Flywheel": ["flywheel"],
            "Cloudways": ["cloudways"],
            "Digital Ocean": ["digitalocean", "digital ocean"],
            "Linode": ["linode"],
            "Vultr": ["vultr"],
            "AWS": ["aws", "amazon web services", "ec2", "s3"],
            "Google Cloud": ["gcp", "google cloud"],
            "Azure": ["azure", "microsoft azure"],
            "Heroku": ["heroku"],
            "Netlify": ["netlify"],
            "Vercel": ["vercel"],
            "Cloudflare": ["cloudflare"],
            "Fastly": ["fastly"],
            "Akamai": ["akamai"],
            "Imperva": ["imperva"],
            "Sucuri": ["sucuri"],
            "Wordfence": ["wordfence"],
            "Cloudflare Workers": ["cloudflare workers"],
            "AWS Lambda": ["lambda"],
            "Azure Functions": ["azure functions"],
            "Google Cloud Functions": ["cloud functions"],
            "Firebase": ["firebase"],
            "Supabase": ["supabase"],
            "Nhost": ["nhost"],
            "Appwrite": ["appwrite"],
            "Back4App": ["back4app"],
            "Parse": ["parse"],
            "Realm": ["realm"],
            "Amplify": ["amplify"],
            "Hasura": ["hasura"],
            "Neon": ["neon.tech", "neon"],
            "PlanetScale": ["planetscale"],
            "Xata": ["xata"],
            "Turso": ["turso"],
            "Upstash": ["upstash"],
            "Fauna": ["fauna"],
            "Convex": ["convex"],
            "Deno Deploy": ["deno deploy"],
            "Cloudflare Pages": ["cloudflare pages"],
            "Cloudflare Workers": ["cloudflare workers"],
            "Fly.io": ["fly.io"],
            "Railway": ["railway"],
            "Render": ["render"],
            "Koyeb": ["koyeb"],
            "Qovery": ["qovery"],
            "Northflank": ["northflank"],
            "Porter": ["porter"],
            "Coolify": ["coolify"],
            "Dokku": ["dokku"],
            "Caprover": ["caprover"],
            "Kubernetes": ["kubernetes", "k8s"],
            "Docker": ["docker"],
            "Podman": ["podman"],
            "Nomad": ["nomad"],
            "Terraform": ["terraform"],
            "Pulumi": ["pulumi"],
            "Ansible": ["ansible"],
            "Chef": ["chef"],
            "Puppet": ["puppet"],
            "Salt": ["salt", "saltstack"],
            "GitHub Actions": ["github actions"],
            "GitLab CI": ["gitlab ci"],
            "CircleCI": ["circleci"],
            "Travis CI": ["travis ci"],
            "Jenkins": ["jenkins"],
            "TeamCity": ["teamcity"],
            "Bamboo": ["bamboo"],
            "Bitbucket Pipelines": ["bitbucket pipelines"],
            "Azure DevOps": ["azure devops"],
            "AWS CodePipeline": ["codepipeline"],
            "Google Cloud Build": ["cloud build"],
            "Drone": ["drone.io", "drone"],
            "Concourse": ["concourse"],
            "Argo CD": ["argo cd", "argocd"],
            "Flux": ["flux"],
            "Spinnaker": ["spinnaker"],
            "Harness": ["harness"],
            "Octopus Deploy": ["octopus deploy"],
            "Buildkite": ["buildkite"],
            "Semaphore": ["semaphore"],
            "Codefresh": ["codefresh"],
            "Buddy": ["buddy"],
            "Appveyor": ["appveyor"],
            "CodeShip": ["codeship"],
            "Wercker": ["wercker"],
            "Shippable": ["shippable"],
            "Nevercode": ["nevercode"],
            "Codemagic": ["codemagic"],
            "Bitrise": ["bitrise"],
            "App Center": ["app center"],
            "Firebase App Distribution": ["firebase app distribution"],
            "TestFlight": ["testflight"],
            "Play Console": ["play console"],
            "Expo": ["expo"],
            "Sentry": ["sentry"],
            "Bugsnag": ["bugsnag"],
            "Rollbar": ["rollbar"],
            "LogRocket": ["logrocket"],
            "Datadog": ["datadog"],
            "New Relic": ["new relic", "newrelic"],
            "Dynatrace": ["dynatrace"],
            "AppDynamics": ["appdynamics"],
            "Elastic APM": ["elastic apm"],
            "Prometheus": ["prometheus"],
            "Grafana": ["grafana"],
            "Kibana": ["kibana"],
            "Loki": ["loki"],
            "Jaeger": ["jaeger"],
            "Zipkin": ["zipkin"],
            "OpenTelemetry": ["opentelemetry"],
            "Instana": ["instana"],
            "Lightstep": ["lightstep"],
            "Honeycomb": ["honeycomb"],
            "Splunk": ["splunk"],
            "Sumo Logic": ["sumo logic"],
            "Logz.io": ["logz.io"],
            "Loggly": ["loggly"],
            "Papertrail": ["papertrail"],
            "Graylog": ["graylog"],
            "Fluentd": ["fluentd"],
            "Logstash": ["logstash"],
            "Vector": ["vector"],
            "OpenSearch": ["opensearch"],
            "Algolia": ["algolia"],
            "Meilisearch": ["meilisearch"],
            "Typesense": ["typesense"],
            "Elasticsearch": ["elasticsearch"],
            "Solr": ["solr"],
            "Vespa": ["vespa"],
            "Weaviate": ["weaviate"],
            "Pinecone": ["pinecone"],
            "Qdrant": ["qdrant"],
            "Milvus": ["milvus"],
            "Chroma": ["chroma"],
            "LanceDB": ["lancedb"],
            "OpenAI": ["openai"],
            "Anthropic": ["anthropic", "claude"],
            "Cohere": ["cohere"],
            "Hugging Face": ["huggingface", "hugging face"],
            "Replicate": ["replicate"],
            "Stability AI": ["stability.ai", "stability ai"],
            "Midjourney": ["midjourney"],
            "Runway": ["runway"],
            "LangChain": ["langchain"],
            "LlamaIndex": ["llamaindex"],
            "Vercel AI SDK": ["vercel ai sdk"],
            "Fixie": ["fixie"],
            "Perplexity": ["perplexity"],
            "Groq": ["groq"],
            "Together AI": ["together.ai", "together ai"],
            "Mistral AI": ["mistral.ai", "mistral ai"],
            "Ollama": ["ollama"],
            "LocalAI": ["localai", "local ai"],
            "LM Studio": ["lm studio"],
            "Jan": ["jan.ai", "jan"],
            "Bedrock": ["bedrock"],
            "Vertex AI": ["vertex ai"],
            "Azure OpenAI": ["azure openai"],
            "Gemini": ["gemini"],
            "GPT": ["gpt"],
            "DALL-E": ["dall-e", "dalle"],
            "Stable Diffusion": ["stable diffusion"],
            "Midjourney": ["midjourney"],
            "Firefly": ["firefly"],
            "Imagen": ["imagen"],
            "Claude": ["claude"],
            "Llama": ["llama"],
            "Mixtral": ["mixtral"],
            "Falcon": ["falcon"],
            "Whisper": ["whisper"],
            "TensorFlow": ["tensorflow"],
            "PyTorch": ["pytorch"],
            "JAX": ["jax"],
            "Keras": ["keras"],
            "scikit-learn": ["scikit-learn", "sklearn"],
            "XGBoost": ["xgboost"],
            "LightGBM": ["lightgbm"],
            "CatBoost": ["catboost"],
            "Pandas": ["pandas"],
            "NumPy": ["numpy"],
            "SciPy": ["scipy"],
            "Matplotlib": ["matplotlib"],
            "Seaborn": ["seaborn"],
            "Plotly": ["plotly"],
            "D3.js": ["d3.js", "d3"],
            "Three.js": ["three.js", "threejs"],
            "Babylon.js": ["babylon.js", "babylonjs"],
            "PlayCanvas": ["playcanvas"],
            "Pixi.js": ["pixi.js", "pixijs"],
            "p5.js": ["p5.js", "p5js"],
            "Paper.js": ["paper.js", "paperjs"],
            "Fabric.js": ["fabric.js", "fabricjs"],
            "Chart.js": ["chart.js", "chartjs"],
            "Highcharts": ["highcharts"],
            "ApexCharts": ["apexcharts"],
            "ECharts": ["echarts"],
            "Recharts": ["recharts"],
            "Victory": ["victory"],
            "Nivo": ["nivo"],
            "Visx": ["visx"],
            "Vega": ["vega"],
            "Vega-Lite": ["vega-lite"],
            "Observable": ["observable"],
            "Leaflet": ["leaflet"],
            "Mapbox": ["mapbox"],
            "OpenLayers": ["openlayers"],
            "Google Maps": ["google maps", "googlemaps"],
            "Maplibre": ["maplibre"],
            "Cesium": ["cesium"],
            "Deck.gl": ["deck.gl", "deckgl"],
            "Kepler.gl": ["kepler.gl", "keplergl"],
            "ArcGIS": ["arcgis"],
            "QGIS": ["qgis"],
            "Turf.js": ["turf.js", "turfjs"],
            "Proj4js": ["proj4js"],
            "Nominatim": ["nominatim"],
            "OpenStreetMap": ["openstreetmap"],
            "HERE": ["here maps", "here"],
            "TomTom": ["tomtom"],
            "Bing Maps": ["bing maps"],
            "Mapbox GL": ["mapbox gl"],
            "Tangram": ["tangram"],
            "Maptiler": ["maptiler"],
            "Stadia Maps": ["stadia maps"],
            "Thunderforest": ["thunderforest"],
            "Carto": ["carto"],
            "Mapzen": ["mapzen"],
            "Jawg": ["jawg"],
            "Geoapify": ["geoapify"],
            "Foursquare": ["foursquare"],
            "Factual": ["factual"],
            "Radar": ["radar.io", "radar"],
            "Esri": ["esri"],
            "Mapillary": ["mapillary"],
            "Strava": ["strava"],
            "Garmin": ["garmin"],
            "Komoot": ["komoot"],
            "Peloton": ["peloton"],
            "Zwift": ["zwift"],
            "Fitbit": ["fitbit"],
            "Apple Health": ["apple health"],
            "Google Fit": ["google fit"],
            "Samsung Health": ["samsung health"],
            "Withings": ["withings"],
            "Oura": ["oura"],
            "Whoop": ["whoop"],
            "Strava": ["strava"],
            "Garmin": ["garmin"],
            "Polar": ["polar"],
            "Suunto": ["suunto"],
            "Coros": ["coros"],
            "MyFitnessPal": ["myfitnesspal"],
            "Cronometer": ["cronometer"],
            "Lifesum": ["lifesum"],
            "Noom": ["noom"],
            "Weight Watchers": ["weight watchers", "ww"],
            "Headspace": ["headspace"],
            "Calm": ["calm"],
            "Waking Up": ["waking up"],
            "Insight Timer": ["insight timer"],
            "Peloton": ["peloton"],
            "Zwift": ["zwift"],
            "TrainerRoad": ["trainerroad"],
            "Sufferfest": ["sufferfest"],
            "Strava": ["strava"],
            "Komoot": ["komoot"],
            "AllTrails": ["alltrails"],
            "Wikiloc": ["wikiloc"],
            "Gaia GPS": ["gaia gps"],
            "Trailforks": ["trailforks"],
            "Relive": ["relive"],
            "Ride with GPS": ["ride with gps"],
            "Wahoo": ["wahoo"],
            "Hammerhead": ["hammerhead"],
            "Karoo": ["karoo"],
            "Garmin": ["garmin"],
            "Suunto": ["suunto"],
            "Polar": ["polar"],
            "Coros": ["coros"],
            "Fitbit": ["fitbit"],
            "Apple Watch": ["apple watch"],
            "Samsung Galaxy Watch": ["galaxy watch"],
            "Withings": ["withings"],
            "Oura": ["oura"],
            "Whoop": ["whoop"],
            "Biostrap": ["biostrap"],
            "Levels": ["levels"],
            "Dexcom": ["dexcom"],
            "Freestyle Libre": ["freestyle libre"],
            "Medtronic": ["medtronic"],
            "Omron": ["omron"],
            "Withings": ["withings"],
            "iHealth": ["ihealth"],
            "Qardio": ["qardio"],
            "Omada": ["omada"],
            "Livongo": ["livongo"],
            "Virta": ["virta"],
            "Noom": ["noom"],
            "Weight Watchers": ["weight watchers", "ww"],
            "Headspace": ["headspace"],
            "Calm": ["calm"],
            "Waking Up": ["waking up"],
            "Insight Timer": ["insight timer"],
            "Talkspace": ["talkspace"],
            "BetterHelp": ["betterhelp"],
            "Cerebral": ["cerebral"],
            "Lyra": ["lyra"],
            "Ginger": ["ginger"],
            "Spring Health": ["spring health"],
            "Modern Health": ["modern health"],
            "Teladoc": ["teladoc"],
            "Amwell": ["amwell"],
            "Doctor on Demand": ["doctor on demand"],
            "MDLIVE": ["mdlive"],
            "Zocdoc": ["zocdoc"],
            "One Medical": ["one medical"],
            "Forward": ["forward"],
            "Carbon Health": ["carbon health"],
            "Parsley Health": ["parsley health"],
            "Tia": ["tia"],
            "Kindbody": ["kindbody"],
            "Maven": ["maven"],
            "Ro": ["ro"],
            "Hims": ["hims"],
            "Hers": ["hers"],
            "Nurx": ["nurx"],
            "Pill Club": ["pill club"],
            "Simple Health": ["simple health"],
            "Lemonaid": ["lemonaid"],
            "GoodRx": ["goodrx"],
            "Blink Health": ["blink health"],
            "Capsule": ["capsule"],
            "Alto": ["alto"],
            "PillPack": ["pillpack"],
            "Truepill": ["truepill"],
            "NowRx": ["nowrx"],
            "ScriptDash": ["scriptdash"],
            "Medly": ["medly"],
            "Instacart": ["instacart"],
            "DoorDash": ["doordash"],
            "Uber Eats": ["uber eats"],
            "Grubhub": ["grubhub"],
            "Postmates": ["postmates"],
            "Caviar": ["caviar"],
            "Seamless": ["seamless"],
            "Deliveroo": ["deliveroo"],
            "Just Eat": ["just eat"],
            "Delivery Hero": ["delivery hero"],
            "Glovo": ["glovo"],
            "Rappi": ["rappi"],
            "iFood": ["ifood"],
            "Swiggy": ["swiggy"],
            "Zomato": ["zomato"],
            "Uber": ["uber"],
            "Lyft": ["lyft"],
            "Bolt": ["bolt"],
            "Grab": ["grab"],
            "Gojek": ["gojek"],
            "Didi": ["didi"],
            "Ola": ["ola"],
            "Careem": ["careem"],
            "BlaBlaCar": ["blablacar"],
            "Via": ["via"],
            "Citymapper": ["citymapper"],
            "Transit": ["transit"],
            "Moovit": ["moovit"],
            "Lime": ["lime"],
            "Bird": ["bird"],
            "Spin": ["spin"],
            "Tier": ["tier"],
            "Voi": ["voi"],
            "Dott": ["dott"],
            "Superpedestrian": ["superpedestrian"],
            "Neuron": ["neuron"],
            "Beam": ["beam"],
            "Nextbike": ["nextbike"],
            "Mobike": ["mobike"],
            "Jump": ["jump"],
            "Citi Bike": ["citi bike"],
            "Divvy": ["divvy"],
            "Capital Bikeshare": ["capital bikeshare"],
            "Bluebikes": ["bluebikes"],
            "Bay Wheels": ["bay wheels"],
            "Biki": ["biki"],
            "Bixi": ["bixi"],
            "Vélib": ["velib"],
            "Santander Cycles": ["santander cycles"],
            "Call a Bike": ["call a bike"],
            "Donkey Republic": ["donkey republic"],
            "Lime": ["lime"],
            "Bird": ["bird"],
            "Spin": ["spin"],
            "Tier": ["tier"],
            "Voi": ["voi"],
            "Dott": ["dott"],
            "Superpedestrian": ["superpedestrian"],
            "Neuron": ["neuron"],
            "Beam": ["beam"],
            "Nextbike": ["nextbike"],
            "Mobike": ["mobike"],
            "Jump": ["jump"],
            "Citi Bike": ["citi bike"],
            "Divvy": ["divvy"],
            "Capital Bikeshare": ["capital bikeshare"],
            "Bluebikes": ["bluebikes"],
            "Bay Wheels": ["bay wheels"],
            "Biki": ["biki"],
            "Bixi": ["bixi"],
            "Vélib": ["velib"],
            "Santander Cycles": ["santander cycles"],
            "Call a Bike": ["call a bike"],
            "Donkey Republic": ["donkey republic"]
        }